version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aldi-sftp-reader"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vzvu9yykv9of"
s3_prefix = "aldi-sftp-reader"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
